version: '3'
services:
  app:
    container_name: nodeserver
    build:
      context: node
      dockerfile: Dockerfile
    networks:
      - node-network
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

    networks:
      - node-network

  nginx:
    #image: nginx
    container_name: nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile.prod

    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - db


networks:
  node-network: 
    driver: bridge